
server:
    port: 10002
    servlet:
        context-path: /api
spring:
  datasource:
    driver-class-name: org.postgresql.Driver  #数据库驱动
    url: jdbc:postgresql://localhost:5432/TestDB #连接地址
    username: postgres #账号
    password: postgres #密码
mybatis-plus:
  # MyBatis 配置文件位置，如果您有单独的 MyBatis 配置，请将其路径配置到 configLocation 中。
  # config-location: classpath:mybatis-config.xml
  # MyBatis Mapper 所对应的 XML 文件位置，如果您在 Mapper 中有自定义方法
  mapper-locations: classpath:mybatisplus/**/*.xml
  # MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package:  online.jianchi.webapi.domain.entity.**.*
  # 启动时是否检查 MyBatis XML 文件的存在，默认不检查
  check-config-location: false
  #  ExecutorType.SIMPLE：该执行器类型不做特殊的事情，为每个语句的执行创建一个新的预处理语句（PreparedStatement）
  #  ExecutorType.REUSE：该执行器类型会复用预处理语句（PreparedStatement）
  #  ExecutorType.BATCH：该执行器类型会批量执行所有的更新语句
  executor-type: simple
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: true
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: null
  global-config:
    #驼峰下划线转换
    column-underline: true
    db-config:
      #      数据库类型,默认值为未知的数据库类型
      #      db-type: mysql
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false